"""Opportunity Finder - rank regions with the tunable scoring model."""

from __future__ import annotations

import plotly.express as px
import streamlit as st

from ndis_explorer.ai import opportunity_insight
from ndis_explorer.opportunity import SUBSCORE_COLUMNS, explain_region, score_regions
from ndis_explorer.streamlit_helpers import (
    configure_page,
    data_source_caption,
    fmt_money,
    fmt_pct,
    get_dataset,
    region_filter_controls,
    sidebar_data_controls,
    weight_controls,
)

configure_page("Opportunity Finder", icon="🎯")
dataset = get_dataset()
sidebar_data_controls(dataset)
weights = weight_controls()
states, remoteness, year = region_filter_controls(dataset)

st.title("🎯 Opportunity Finder")
data_source_caption(dataset)
st.markdown(
    "Regions ranked by a **transparent weighted score** combining market size, "
    "growth, under-servicing and the utilisation gap. Tune the weights and "
    "filters in the sidebar."
)

scored = score_regions(
    dataset, weights=weights, year=year,
    states=states or None, remoteness=remoteness or None,
)

if scored.empty:
    st.warning("No regions match the current filters.")
    st.stop()

# --- Bubble chart: market size vs supply, coloured by score ------------- #
st.subheader("Opportunity landscape")
fig = px.scatter(
    scored,
    x="participants_per_provider",
    y="utilisation",
    size="committed_supports",
    color="opportunity_score",
    hover_name="region_name",
    color_continuous_scale="Turbo",
    labels={
        "participants_per_provider": "Participants per provider (thin supply →)",
        "utilisation": "Utilisation (← unmet need)",
        "opportunity_score": "Score",
    },
    custom_data=["state", "opportunity_score"],
)
fig.update_yaxes(tickformat=".0%")
fig.update_traces(
    hovertemplate=(
        "<b>%{hover_name}</b> (%{customdata[0]})<br>"
        "Participants/provider: %{x:.0f}<br>"
        "Utilisation: %{y:.0%}<br>"
        "Score: %{customdata[1]:.0f}<extra></extra>"
    )
)
st.plotly_chart(fig, use_container_width=True)
st.caption("Bubble size = committed supports. Bottom-right + warm colour = best.")

# --- Ranked table ------------------------------------------------------- #
st.subheader("Ranked regions")
table = scored.assign(
    Committed=lambda d: d["committed_supports"].map(fmt_money),
    Utilisation=lambda d: d["utilisation"].map(fmt_pct),
    Growth=lambda d: d["participant_cagr"].map(fmt_pct),
    PPP=lambda d: d["participants_per_provider"].round(0),
    Score=lambda d: d["opportunity_score"].round(1),
)[
    [
        "opportunity_rank", "region_name", "state", "remoteness",
        "active_participants", "Committed", "Utilisation", "Growth", "PPP",
        "Score",
    ]
].rename(
    columns={
        "opportunity_rank": "Rank",
        "region_name": "Region",
        "state": "State",
        "remoteness": "Remoteness",
        "active_participants": "Participants",
    }
)
st.dataframe(
    table,
    hide_index=True,
    use_container_width=True,
    column_config={
        "Score": st.column_config.ProgressColumn(
            "Score", min_value=0, max_value=100, format="%.0f"
        )
    },
)

# --- Drill into a region ------------------------------------------------ #
st.subheader("Why does a region score well?")
choice = st.selectbox("Pick a region", scored["region_name"].tolist())
row = scored[scored["region_name"] == choice].iloc[0]
exp = explain_region(row)

cols = st.columns(4)
cols[0].metric("Opportunity score", f"{exp['opportunity_score']:.0f}/100")
cols[1].metric("Participants", f"{int(exp['participants']):,}")
cols[2].metric("Utilisation", fmt_pct(exp["utilisation"]))
cols[3].metric("Participants/provider", f"{exp['participants_per_provider']:.0f}")

driver_df = (
    row[SUBSCORE_COLUMNS]
    .rename(
        {
            "score_market_size": "Market size",
            "score_growth": "Growth",
            "score_underservice": "Under-servicing",
            "score_utilisation_gap": "Utilisation gap",
        }
    )
    .reset_index()
)
driver_df.columns = ["Driver", "Sub-score"]
fig = px.bar(
    driver_df, x="Sub-score", y="Driver", orientation="h", range_x=[0, 100],
    color="Sub-score", color_continuous_scale="Turbo",
)
fig.update_layout(coloraxis_showscale=False)
st.plotly_chart(fig, use_container_width=True)

# --- Narrative insight -------------------------------------------------- #
st.subheader("📝 Auto-generated brief")
use_llm = st.toggle("Use LLM if available", value=True,
                    help="Falls back to a rule-based brief when no API key.")
result = opportunity_insight(scored, n=5, use_llm=use_llm)
st.markdown(result.text)
st.caption(f"Generated by: {result.backend} backend.")

st.download_button(
    "Download ranked regions (CSV)",
    data=scored.to_csv(index=False).encode("utf-8"),
    file_name=f"ndis_opportunities_{year}.csv",
    mime="text/csv",
)
