"""Regional Explorer - drill into a single service region."""

from __future__ import annotations

import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

from ndis_explorer.ai import region_insight
from ndis_explorer.analysis import demographic_summary
from ndis_explorer.opportunity import score_regions
from ndis_explorer.streamlit_helpers import (
    configure_page,
    data_source_caption,
    fmt_money,
    fmt_pct,
    get_dataset,
    sidebar_data_controls,
)

configure_page("Regional Explorer", icon="🗺️")
dataset = get_dataset()
sidebar_data_controls(dataset)

st.title("🗺️ Regional Explorer")
data_source_caption(dataset)

# Region picker (grouped by state for usability).
regions = dataset.regions.sort_values(["state", "region_name"])
labels = {
    rid: f"{name} ({state})"
    for rid, name, state in zip(
        regions["region_id"], regions["region_name"], regions["state"]
    )
}
region_id = st.selectbox(
    "Region", options=regions["region_id"].tolist(),
    format_func=lambda r: labels[r],
)

scored = score_regions(dataset)  # national peer group for fair scoring
row = scored[scored["region_id"] == region_id].iloc[0]
meta = dataset.region_lookup().loc[region_id]

st.header(f"{meta['region_name']}  ·  {meta['state']}")
st.caption(f"{meta['remoteness']} · population ≈ {int(meta['population']):,}")

c = st.columns(5)
c[0].metric("Opportunity score", f"{row['opportunity_score']:.0f}/100",
            help=f"National rank #{int(row['opportunity_rank'])}")
c[1].metric("Participants", f"{int(row['active_participants']):,}")
c[2].metric("Committed", fmt_money(row["committed_supports"]))
c[3].metric("Utilisation", fmt_pct(row["utilisation"]))
c[4].metric("Participants/provider", f"{row['participants_per_provider']:.0f}")

st.divider()

# --- Trends for this region -------------------------------------------- #
st.subheader("History")
mkt = dataset.market[dataset.market["region_id"] == region_id].sort_values("year")
prov = dataset.providers[dataset.providers["region_id"] == region_id].sort_values("year")
hist = mkt.merge(prov, on=["region_id", "year"], how="left")
hist["utilisation"] = (hist["payments"] / hist["committed_supports"]).clip(0, 1)

col1, col2 = st.columns(2)
with col1:
    fig = go.Figure()
    fig.add_bar(x=hist["year"], y=hist["committed_supports"], name="Committed",
                marker_color="#93c5fd")
    fig.add_bar(x=hist["year"], y=hist["payments"], name="Paid",
                marker_color="#2563eb")
    fig.update_layout(barmode="overlay", title="Funding", yaxis_title="AUD",
                      xaxis_title="Year")
    st.plotly_chart(fig, use_container_width=True)
with col2:
    fig = go.Figure()
    fig.add_scatter(x=hist["year"], y=hist["active_participants"],
                    name="Participants", line_color="#2563eb")
    fig.add_scatter(x=hist["year"], y=hist["active_providers"],
                    name="Providers", line_color="#f59e0b", yaxis="y2")
    fig.update_layout(
        title="Demand vs supply",
        xaxis_title="Year",
        yaxis=dict(title="Participants"),
        yaxis2=dict(title="Providers", overlaying="y", side="right"),
        legend=dict(orientation="h"),
    )
    st.plotly_chart(fig, use_container_width=True)

st.divider()

# --- Local demographics ------------------------------------------------ #
st.subheader("Participant mix (latest year)")
d1, d2, d3 = st.columns(3)
for col, seg_type, title in (
    (d1, "disability_type", "Disability type"),
    (d2, "age_band", "Age band"),
    (d3, "plan_management", "Plan management"),
):
    summ = demographic_summary(dataset, seg_type, region_ids=[region_id])
    with col:
        fig = px.pie(summ, names="segment", values="participants", title=title,
                     hole=0.45)
        fig.update_layout(showlegend=False)
        fig.update_traces(textinfo="label+percent", textposition="inside")
        st.plotly_chart(fig, use_container_width=True)

st.divider()
st.subheader("📝 Region brief")
use_llm = st.toggle("Use LLM if available", value=True)
result = region_insight(row, use_llm=use_llm)
st.markdown(result.text)
st.caption(f"Generated by: {result.backend} backend.")
